services:
  - type: web
    name: newsletter-processor
    env: python
    buildCommand: |
      pip install -U pip
      pip install numpy==1.24.3
      pip install scipy==1.10.1
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0